[MSYS-641] Fixed specs for 'internet_gateway', 'vpc', 'key_pair', 'network_acl' and 'network_interface' resources
MsysTechnologiesllc/chef-provisioning-aws pull request #19
Opened 2017-08-18 12:01 UTC by NAshwini

Fixed spec for 'internet_gateway', 'vpc', 'key_pair', 'network_acl' and 'network_interface' resources

Signed-off-by: NAshwini <ashwini.nehate@msystechnologies.com>

2017-08-22 13:17 UTC, NimishaS requested changes

2017-08-22 13:17 UTC, NimishaS commented on lib/chef/provider/aws_network_interface.rb
> +      option1 = options.dup.tap { |h| h.delete(:device_index) }
It would be good to use some other name than `option1`.

2017-08-22 13:17 UTC, NimishaS commented on lib/chef/provider/aws_vpc.rb
> +              ig_tag = current_ig.tags.find{|i|i.key=='OwnedByVPC'}
Please share some sample value of `current_ig.tags`. It looks like it's not a hash now.

2017-08-22 13:17 UTC, NimishaS commented on lib/chef/provider/aws_vpc.rb
> +    current_route_table = main_route_table if current_route_table.nil?
This can be written as:
```current_route_table ||= main_route_table```

2017-08-22 13:17 UTC, NimishaS commented on spec/aws_support/deep_matcher/match_values_failure_messages.rb
> +            elsif expected_key.to_s == "internet_gateways_entries"
Since there are several `If-Else` conditions, we can use `switch` here.

2017-08-23 10:38 UTC, dheerajd-msys commented on lib/chef/provider/aws_vpc.rb
> +          ig_tag = ig.tags.find{|i|i.key=='OwnedByVPC'}
This line could be replaced by ig_tag = ig.tags.find { |i|i.key == "OwnedByVPC" }

2017-08-23 10:40 UTC, Vasu1105 reviewed
since in ruby string interpolation is widely used over string concatenation I will prefer if you use that.

2017-08-23 10:42 UTC, dheerajd-msys commented on lib/chef/provider/aws_vpc.rb
> +              ig_tag = current_ig.tags.find{|i|i.key=='OwnedByVPC'}
[Style] need space between `find` and `{`  and each side of  `==` like my above comment.

2017-08-23 10:43 UTC, dheerajd-msys commented on lib/chef/provider/aws_vpc.rb
> +              ig_tag = current_ig.tags.find{|i|i.key=='OwnedByVPC'}
Same as my above comments.

2017-08-23 12:42 UTC, harikesh-kolekar approved these changes

2017-08-29 10:41 UTC, NimishaS approved these changes

2017-08-29 12:33 UTC, merged